version: "3.8"

services:
  api:
    image: bukkerohithmarthandanaik/fastapi
    ports:
      - "80:8000"
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8000 
    env_file:
      - ./.env
    environment:
      - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
      - DATABASE_PORT=${DATABASE_PORT}
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER={DATABASE_USERNAME}
      - POSTGRES_PASSWORD={DATABASE_PASSWORD}
      - POSTGRES_DB={DATATBASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

    ports:
      - "5432:5432"

volumes:
  postgres_data:

